---
# tasks file for virt-host package installation

- name: Update apt repositories cache
  become: true
  apt:
    update_cache: yes

- name: Install apt network packages
  become: true
  apt:
    name: [ bridge-utils, openssh-server ]
    state: present

- name: Install apt filesystem packages
  become: true
  apt:
    name: [ gdisk, zfsutils-linux ]
    state: present

- name: Install apt virtualization packages
  become: true
  apt:
    name: [ qemu-kvm, libvirt-bin, virtinst, ovmf ]
    state: present

- name: Install apt ansible support packages
  become: true
  apt:
    name: python-lxml
    state: present
